activities/urls.py
from django.urls import path

from . import views

app_name = 'activities'

urlpatterns = [
    path('activities', views.activities, name='activities'),
    path('saveactivities', views.saveactivities),
    path('saveparticipant/<int:kegiatan_id>', views.saveparticipant)
]

karinaa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('profile', include('story1.urls')),
    path('', include('activities.urls')),
    path('', include('story8.urls')),
]

main/urls.py
from django.urls import path

from . import views
app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('moments', views.moments, name='moments'),
    path('contact', views.contact, name='contact'),
    path('course', views.course, name='course'),
    path('savecourse', views.savecourse),
    path('deletecourse/<str:nama_matkul>', views.deletecourse),
    path('coursedetails/<str:nama_matkul>', views.coursedetails),
    path('register', views.register, name='register'),
    path('login', views.loginuser, name='login'),
    path('logout', views.logoutuser, name='logout'),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.profile, name='profile'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('searchbooks', views.searchbooks, name='searchbooks'),
    path('data/', views.data)
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- My Font-->
    <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cormorant:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block meta %}
    {% endblock meta %}
  </head>

  <body>
    
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">Karinaap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-0">
            {% if user.is_authenticated %}
            <a class="nav-link" href="#"><span class="fa fa-user"></span> Hallo, {{ user.get_username }}!</a>
            <a class="nav-link" href="logout"><span class="fa fa-sign-out"></span> Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'main:register' %}"><span class="fa fa-user"></span> Sign Up</a>
            <a class="nav-link" href="{% url 'main:login' %}"><span class="fa fa-sign-in"></span> Login</a>
            {% endif %}
          </div>
          <div class="navbar-nav ml-auto">
            <a class="nav-link {% if navbar == 'home' %}active{% endif %}" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-link {% if navbar == 'profile' %}active{% endif %}" href="{% url 'story1:profile' %}">Profile</a>
            <li class="nav-item dropdown">
              <a class="nav-link {% if navbar == 'activities' or navbar == 'moments' %}active{% endif %} dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Activities
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'activities:activities' %}">Activities</a>
                <a class="dropdown-item" href="{% url 'main:moments' %}">Moments</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link {% if navbar == 'course' or navbar == 'searchbooks' %}active{% endif %} dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Course
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'main:course' %}">Course</a>
                <a class="dropdown-item" href="{% url 'story8:searchbooks' %}">Search Books</a>
              </div>
            </li>
            <a class="nav-link {% if navbar == 'contact' %}active{% endif %}" href="{% url 'main:contact' %}">Contact</a>
            
            
            <!-- <a class="nav-link {% if navbar == 'moments' %}active{% endif %}" href="{% url 'main:moments' %}">Moments</a> -->
            <!-- <a class="nav-link {% if navbar == 'course' %}active{% endif %}" href="{% url 'main:course' %}">Course</a> -->
            <!-- <a class="nav-link {% if navbar == 'activities' %}active{% endif %}" href="{% url 'activities:activities' %}">Activities</a> -->
            <!-- <a class="nav-link {% if navbar == 'searchbooks' %}active{% endif %}" href="{% url 'story8:searchbooks' %}">Search Books</a> -->
          </div>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    {% block script %}
    {% endblock script %}
  </body>

  
</html>